-- ApexFund — table definitions (PostgreSQL)
--
-- Mirrors the SQLAlchemy models in backend_jitendra/app/models.py. Table,
-- column and constraint names are kept identical to what SQLAlchemy's
-- create_all() would emit, so the two paths cannot drift apart.
--
-- Safe to re-run: every statement is guarded with IF NOT EXISTS.
--
-- Identity columns use GENERATED BY DEFAULT (not ALWAYS) so seed and migration
-- scripts can insert explicit ids when they need to.

BEGIN;

-- ---------------------------------------------------------------------------
-- users — registered traders. Replaces the apexfund_users localStorage array.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(120) NOT NULL,
    email         varchar(255) NOT NULL,
    -- Format: pbkdf2_sha256$<iterations>$<salt_hex>$<digest_hex>.
    -- Never store or log a plaintext password.
    password_hash varchar(255) NOT NULL,
    is_active     boolean      NOT NULL DEFAULT true,
    created_at    timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT ck_users_name_not_blank  CHECK (btrim(name) <> ''),
    CONSTRAINT ck_users_email_shape     CHECK (email LIKE '%_@_%')
);

-- ---------------------------------------------------------------------------
-- plans — the challenge catalogue. Replaces the PLANS array in js/data.js.
-- The text id ("two-step-20000") is the same value the frontend puts in
-- checkout.html?plan=..., so it stays the primary key rather than a surrogate.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS plans (
    id                 varchar(60) PRIMARY KEY,
    eval_label         varchar(80) NOT NULL,
    eval_steps         integer     NOT NULL,
    account_size       integer     NOT NULL,
    original_price     integer     NOT NULL,
    price              integer     NOT NULL,
    profit_split       integer     NOT NULL,
    phase1_profit_pct  integer     NOT NULL,
    phase2_profit_pct  integer     NOT NULL,
    max_daily_loss_pct integer     NOT NULL,
    max_total_loss_pct integer     NOT NULL,
    most_popular       boolean     NOT NULL DEFAULT false,
    is_active          boolean     NOT NULL DEFAULT true,
    sort_order         integer     NOT NULL DEFAULT 0,

    CONSTRAINT ck_plans_eval_steps    CHECK (eval_steps BETWEEN 1 AND 3),
    CONSTRAINT ck_plans_account_size  CHECK (account_size > 0),
    CONSTRAINT ck_plans_price         CHECK (price >= 0 AND original_price >= 0),
    -- The pricing table renders original_price struck through next to price.
    CONSTRAINT ck_plans_discount      CHECK (price <= original_price),
    CONSTRAINT ck_plans_profit_split  CHECK (profit_split BETWEEN 0 AND 100),
    CONSTRAINT ck_plans_phase1_pct    CHECK (phase1_profit_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_plans_phase2_pct    CHECK (phase2_profit_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_plans_daily_loss    CHECK (max_daily_loss_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_plans_total_loss    CHECK (max_total_loss_pct BETWEEN 0 AND 100),
    -- A daily cap above the total cap could never bind.
    CONSTRAINT ck_plans_loss_ordering CHECK (max_daily_loss_pct <= max_total_loss_pct)
);

-- ---------------------------------------------------------------------------
-- accounts — simulated challenge accounts. Replaces apexfund_accounts.
--
-- eval_label, account_size and profit_split are copied from the plan at
-- purchase time on purpose: an account must keep the terms it was sold under
-- even if the plan is later repriced or withdrawn.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounts (
    id           integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer       NOT NULL,
    plan_id      varchar(60)   NOT NULL,
    eval_label   varchar(80)   NOT NULL,
    account_size integer       NOT NULL,
    profit_split integer       NOT NULL,
    phase        varchar(20)   NOT NULL DEFAULT 'Step 1',
    status       varchar(20)   NOT NULL DEFAULT 'active',
    balance      numeric(14,2) NOT NULL,
    created_at   timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    -- No ON DELETE action: a plan that has been sold must not be deletable.
    CONSTRAINT accounts_plan_id_fkey FOREIGN KEY (plan_id)
        REFERENCES plans (id),

    CONSTRAINT ck_accounts_phase        CHECK (phase IN ('Step 1', 'Step 2', 'Funded')),
    CONSTRAINT ck_accounts_status       CHECK (status IN ('active', 'passed', 'failed', 'breached')),
    CONSTRAINT ck_accounts_size         CHECK (account_size > 0),
    CONSTRAINT ck_accounts_balance      CHECK (balance >= 0),
    CONSTRAINT ck_accounts_profit_split CHECK (profit_split BETWEEN 0 AND 100)
);

-- ---------------------------------------------------------------------------
-- orders — simulated purchases.
--
-- Only the last four digits of the card are ever stored. The full number,
-- expiry and CVC are validated in the API layer and then discarded; there is no
-- column for them here, deliberately.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id           integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference    varchar(40)   NOT NULL,
    user_id      integer       NOT NULL,
    plan_id      varchar(60)   NOT NULL,
    account_id   integer,
    full_name    varchar(120)  NOT NULL,
    email        varchar(255)  NOT NULL,
    amount       numeric(12,2) NOT NULL,
    currency     varchar(3)    NOT NULL DEFAULT 'INR',
    status       varchar(20)   NOT NULL DEFAULT 'paid',
    card_last4   varchar(4)    NOT NULL,
    agreed_rules boolean       NOT NULL DEFAULT false,
    created_at   timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT orders_plan_id_fkey FOREIGN KEY (plan_id)
        REFERENCES plans (id),
    -- Keep the receipt even if the account it opened is removed.
    CONSTRAINT orders_account_id_fkey FOREIGN KEY (account_id)
        REFERENCES accounts (id) ON DELETE SET NULL,

    CONSTRAINT ck_orders_amount     CHECK (amount >= 0),
    CONSTRAINT ck_orders_currency   CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_orders_status     CHECK (status IN ('pending', 'paid', 'failed', 'refunded')),
    CONSTRAINT ck_orders_card_last4 CHECK (card_last4 ~ '^[0-9]{4}$'),
    -- checkout.html gates the pay button on the rules checkbox; a paid order
    -- must therefore always carry the acknowledgement.
    CONSTRAINT ck_orders_paid_agreed CHECK (status <> 'paid' OR agreed_rules)
);

-- ---------------------------------------------------------------------------
-- payouts — the dashboard's payout history table.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payouts (
    id          integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  integer       NOT NULL,
    payout_date date          NOT NULL,
    amount      numeric(12,2) NOT NULL,
    status      varchar(20)   NOT NULL DEFAULT 'processing',
    created_at  timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT payouts_account_id_fkey FOREIGN KEY (account_id)
        REFERENCES accounts (id) ON DELETE CASCADE,

    -- One payout per account per day; also the natural idempotency key when
    -- the demo payout schedule is re-applied.
    CONSTRAINT uq_payout_account_date UNIQUE (account_id, payout_date),

    CONSTRAINT ck_payouts_amount CHECK (amount >= 0),
    CONSTRAINT ck_payouts_status CHECK (status IN ('paid', 'processing', 'failed'))
);

-- ---------------------------------------------------------------------------
-- contact_messages — homepage "Need help? Contact us" submissions.
-- Replaces the contactMessages localStorage key.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
    id         integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(120) NOT NULL,
    mobile     varchar(30)  NOT NULL,
    email      varchar(255) NOT NULL,
    message    text,
    is_handled boolean      NOT NULL DEFAULT false,
    created_at timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT ck_contact_name_not_blank   CHECK (btrim(name) <> ''),
    CONSTRAINT ck_contact_mobile_not_blank CHECK (btrim(mobile) <> ''),
    CONSTRAINT ck_contact_email_shape      CHECK (email LIKE '%_@_%')
);

COMMENT ON TABLE users            IS 'Registered traders. Passwords are PBKDF2-SHA256 hashes.';
COMMENT ON TABLE plans            IS 'Challenge plan catalogue; ids are the slugs used in checkout URLs.';
COMMENT ON TABLE accounts         IS 'Simulated challenge accounts, holding a snapshot of the plan terms sold.';
COMMENT ON TABLE orders           IS 'Simulated purchases. Stores only the last four card digits.';
COMMENT ON TABLE payouts          IS 'Payout history rendered by the dashboard.';
COMMENT ON TABLE contact_messages IS 'Contact form submissions; contains personal data.';

COMMENT ON COLUMN accounts.balance      IS 'Simulated balance; opens equal to account_size.';
COMMENT ON COLUMN accounts.eval_label   IS 'Snapshot of plans.eval_label at purchase time.';
COMMENT ON COLUMN orders.card_last4     IS 'Last four digits only. Full PAN is never persisted.';
COMMENT ON COLUMN orders.reference      IS 'Human-quotable receipt id, e.g. AF-9F2C1B0A44D1.';

COMMIT;
